version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: purple_star_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app 